name: "Ventra EMS"
description: "Ventra-tech Energy Management System"
version: "1.0.424"
slug: "ventra_ems_v2"
image: "ghcr.io/frank8the9tank/ventra-ems/{arch}"
url: "https://github.com/frank8the9tank/Ventra-EMS"
changelog: "CHANGELOG.md"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
auth_api: true
homeassistant_api: true
supervisor_api: true
ingress: true
ingress_port: 8125
ports:
  8125/tcp: 8125
panel_icon: "mdi:home-battery-outline"
panel_title: "Ventra EMS"
map:
  - config:rw
options:
  logging: false
  license_key: ""
schema:
  logging: bool
  license_key: str
